## Morphological Transformations

In [15]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [16]:
img = cv2.imread('j.png',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

In [17]:
dilation = cv2.dilate(img,kernel,iterations = 1)

In [18]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

In [19]:
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [20]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [21]:
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)


In [22]:
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [ ]:
cv2.namedWindow('res1')
cv2.namedWindow('res2')
cv2.namedWindow('res3')
cv2.namedWindow('res4')
cv2.namedWindow('res5')
cv2.namedWindow('res6')

while(1):
    cv2.imshow('res1',dilation)
    cv2.imshow('res2',opening)
    cv2.imshow('res3',closing)
    cv2.imshow('res4',gradient)
    cv2.imshow('res5',tophat)
    cv2.imshow('res6',blackhat)
    if cv2.waitKey(20) & 0xFF == 27:
        break
cv2.destroyAllWindows()

In [ ]:
# Rectangular Kernel
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
array([[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1]], dtype=uint8)
# Elliptical Kernel
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
array([[0, 0, 1, 0, 0],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[0, 0, 1, 0, 0]], dtype=uint8)
# Cross-shaped Kernel
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
array([[0, 0, 1, 0, 0],
[0, 0, 1, 0, 0],
[1, 1, 1, 1, 1],
[0, 0, 1, 0, 0],
[0, 0, 1, 0, 0]], dtype=uint8)

NameError: name 'array' is not defined